### ISSUE TITLE
Any chance of releasing wheel packages?

### ISSUE THREAD

**Issue by graingert** [gitpython-developers/smmap#28]

**Comment by Byron** [comment]
I do not understand this question. Can you elaborate ?

**Comment by Byron** [comment]
I think I understand now, it's about [python wheels](http://pythonwheels.com/), a new standard.

As you have added a patch for gitdb already, do you think the same is possible for smmap and gitpython respectively ?
(_At this point I am depending on contributions for new features, and will only fix certain bugs._)

**Comment by graingert** [comment]
As discussed, they're already patched. They just need a new release https://github.com/gitpython-developers/gitdb/pull/29#issuecomment-246168635

**Comment by graingert** [comment]
https://github.com/gitpython-developers/GitPython/issues/511

**Comment by EliahKagan** [comment]
Is this issue resolved? It seems smmap has had wheels on PyPI for a while now (not just [recently](https://pypi.org/project/smmap/#files) but, for example, [a couple years ago](https://pypi.org/project/smmap/5.0.0/#files)).

**Comment by Byron** [comment]
This is a very old issue - hence let's close it proactively. If this is still an issue, comments on why that is are definitely welcome.
