### ISSUE TITLE
PyPi missing LICENSE

### ISSUE THREAD

**Issue by lafrenierejm** [gitpython-developers/smmap#35]
The [project on PyPi](https://pypi.python.org/pypi/smmap2/2.0.1) is missing the LICENSE file.

**Comment by Byron** [comment]
Thanks for letting me know. Following your link, all I see is what looks like a license specification to me.
<img width="983" alt="screen shot 2017-02-25 at 09 49 34" src="https://cloud.githubusercontent.com/assets/63622/23329799/ec39873e-fb3f-11e6-9f0f-cc0792b3b82b.png">
If you think more is needed, maybe you can submit a PR for a fix.
